# Generated by Django 5.0.7 on 2024-08-19 07:57

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sessionyearmodel",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="adminhod",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
