# Generated by Django 5.0.7 on 2024-08-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "realstudentapp",
            "0002_subjects_staffs_id_alter_adminhod_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="Staffs_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="realstudentapp.staffs"
            ),
        ),
    ]
