# Generated by Django 5.0.7 on 2024-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0002_alter_sessionyearmodel_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
