# Generated by Django 5.0.7 on 2024-09-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0003_alter_attendance_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffs",
            name="fcm_token",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="students",
            name="fcm_token",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leavereportstaff",
            name="leave_status",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OnlineClassRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                ("room_pwd", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "session_years",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realstudentapp.sessionyearmodel",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realstudentapp.staffs",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realstudentapp.subjects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_exam_marks", models.FloatField(default=0)),
                ("subject_assignment_marks", models.FloatField(default=0)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realstudentapp.students",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realstudentapp.subjects",
                    ),
                ),
            ],
        ),
    ]
