# Generated by Django 5.0.7 on 2024-08-04 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0003_alter_subjects_staffs_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjects",
            old_name="Staffs_id",
            new_name="Staff_id",
        ),
    ]
