# Generated by Django 5.0.7 on 2024-08-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0004_rename_staffs_id_subjects_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staffs",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
