# Generated by Django 5.0.7 on 2024-08-08 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realstudentapp", "0006_alter_subjects_staff_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjects",
            old_name="Staff_id",
            new_name="staff_id",
        ),
    ]
